<li class="list-group-item"><span class="btn btn-danger btn-xs">1</span> 多款APP开放报名内测啦，欢迎您前来报名体验！</li>
<li class="list-group-item"><span class="btn btn-success btn-xs">2</span> 温馨提示：内测会保护个人隐私，所有个人信息不会泄露！</li>
<li class="list-group-item"><span class="btn btn-info btn-xs">3</span> 发现更多问题即可获得丰富奖励~</li>
<li class="list-group-item"><span class="btn btn-warning btn-xs">4</span> 内测过程中会全量打印日志，遇到问题请上报相关日志，感谢您的支持！</li>
<li class="list-group-item"><span class="btn btn-primary btn-xs">5</span> 特别提醒：内测过程请严格遵守内测守则，违规者取消内测资格，严重违规将被封号处理！</li>
<li class="list-group-item"><span class="btn btn-danger btn-xs">6</span> 预祝大家在内测过程中合作愉快！</li>
<div class="btn-group btn-group-justified">
    <a target="_blank" class="btn btn-info" href="//wpa.qq.com/msgrd?v=3&amp;uin=544901005&amp;site=qq&amp;menu=yes"><i class="fa fa-qq"></i> 联系客服</a>
    <a target="_blank" class="btn btn-warning" href="///jq.qq.com/?_wv=1027&amp;k=56HV5UT"><i class="fa fa-users"></i> 官方Q群</a>
    <a target="_blank" class="btn btn-danger" href="//update.meternity.cn/reptile"><i class="fa fa-cloud-download"></i> APP下载</a>
</div>
